### ISSUE TITLE
Debian and Missing Network Manager Applet

### ISSUE THREAD

**Issue by johnsonmt01** [AyatanaIndicators/libayatana-appindicator-glib#41]
Testing Ayatana indicators on Debian 11 Bullseye (MATE desktop).  When Ayatana synaptic packages are installed, I get every indicator working except for the Network Manager Applet.  This applet appears as an indicator in Ubuntu Mate, but does not appear in Debian.  I can substitute by using the NM-Tray applet, but at a loss of functionality. Am I missing packages separate from Ayatana that may enable this?  Thank you.

**Comment by ghost** [comment]
A lot of applications still use the old and deprecated libappindicator instead of libayatana-appindicator. Some Linux distributions still ship libappindicator, so the MATE indicator applet can display these applications alonside those that use Ayatana.

Since libappindicator is not in Debian anymore, all Debian users can do is wait until developers adapt their apps... Let's call it a transition period.

**Comment by sunweaver** [comment]
@johnsonmt01 @tari01 The reason for your issue with nm-applet is, that in Debian nm-applet.desktop simple launches "nm-applet" whereas Ubuntu's version launches "nm-applet --indicator". You can copy nm-applet.desktop from /usr/share/applications to either /etc/xdg/autostart or ~/.config/autostart and adjust the Exec= key in the file accordingly:

```
[sunweaver@sunobo .config]$ diff -u /usr/share/applications/nm-applet.desktop autostart/nm-applet.desktop 
--- /usr/share/applications/nm-applet.desktop	2021-02-27 20:11:20.000000000 +0100
+++ autostart/nm-applet.desktop	2021-12-17 09:52:19.065194599 +0100
@@ -141,7 +141,7 @@
 Comment[zh_TW]=管理您的網路連線
 Comment=Manage your network connections
 Icon=nm-device-wireless
-Exec=nm-applet
+Exec=nm-applet --indicator
 Terminal=false
 Type=Application
 NoDisplay=true
```

Please let me know if that helps...

**Comment by johnsonmt01** [comment]
Sunweaver, that worked perfectly, thank you!
