### ISSUE TITLE
Can't build for GTK+-3 without having python-2, pygtk, and pygobobject installed

### ISSUE THREAD

**Issue by g92k** [AyatanaIndicators/libayatana-appindicator-glib#5]
I'm building from source and only want to build for GTK+-3.  These packages are not needed for that.

**Comment by gllmhyt** [comment]
@g92k Here's the lines checking for Python https://github.com/AyatanaIndicators/libayatana-appindicator/blob/5ca235fa311883b332d9496acc901bee7662b3b5/configure.ac#L189

We can either remove it because Python 2 being EOL, or make them optional because we don't need to check when not building the python2. I have never written a configure.ac file, but reading it I think this is what is done in the Mono part: https://github.com/AyatanaIndicators/libayatana-appindicator/blob/5ca235fa311883b332d9496acc901bee7662b3b5/configure.ac#L110 resulting in the "checking for MONO_DEPENDENCY..." in configuration.

**Comment by sunweaver** [comment]
This has been resolved with recent commits (unfortunately more than one), the version with Python2 fully removed is https://github.com/AyatanaIndicators/libayatana-appindicator/commit/05ebffc454af9e8a04513c659366a6c1dee6b856
