### ISSUE TITLE
libayatana-appindicator 0.5.90-7 breaks libappindicator3-1

### ISSUE THREAD

**Issue by AO-L10N** [AyatanaIndicators/libayatana-appindicator-glib#53]
On Ubuntu 22.04 (Jammy) the latest libayatana-appindicator3-1 and gir1.2-ayatanaappindicator3-0.1 0.5.90-7 broke libappindicator3-1, gir1.2-appindicator3-0.1and related apps like  indicator-application.

**Comment by seb128** [comment]
https://www.debian.org/doc/debian-policy/ch-relationships.html#s-replaces documents using unversioned Conflicts/Replaces/Provides. The version used in the change is also weird since it doesn't match the version of libayatana-appindicator nor of libappindicator from Debian nor Ubuntu

I've uploaded a fix to Ubuntu, let's see it's enough

http://launchpadlibrarian.net/593503199/libayatana-appindicator_0.5.90-7_0.5.90-7ubuntu1.diff.gz

**Comment by seb128** [comment]
In fact that was the issue, but that's the problem, other components have depends as

Depends: libappindicator3-1 (>= 0.2.92),

or an unversioned provides are not going to be considered valid for that depends. versioning the provides made it work, http://launchpadlibrarian.net/593526897/libayatana-appindicator_0.5.90-7ubuntu1_0.5.90-7ubuntu2.diff.gz (12.10 used as a version to match what libappindicator had in Ubuntu)

**Comment by flexiondotorg** [comment]
Tagging @sunweaver. See above :point_up:

**Comment by sunweaver** [comment]
@seb128 @flexiondotorg Will provide seb128's fix in Debian directly. Thanks!

**Comment by sunweaver** [comment]
@seb128 @flexiondotorg Just uploaded to Debian as 0.5.90-8. Thanks!
